version: '3.1'

services:
  stats-server:
    build: stat/stat_service
    image: stat_service
    container_name: stat_service
    ports:
      - "9090:9090"
      - "5005:5005"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stat
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ewm-stats
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005

  stats-db:
    image: postgres:15.1-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=stat

  ewm-service:
    build: main_server
    image: main_server
    container_name: main_server
    ports:
      - "8080:8080"